### ISSUE TITLE
error:malformed calendar; expected end

### ISSUE THREAD

**Issue by KirillZet** [arran4/golang-ical#111]
### Current Behavior:

Hello, I'm trying to parse a calendar using your library.
Calendar obtained via http.
Here's my code:

	icalURL := "http://english.mirea.ru/schedule/api/ical/1/248"

	resp, err := http.Get(icalURL)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	fmt.Println("Raw iCal data:")
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(body))

	calendar, err := ics.ParseCalendar(strings.NewReader(string(body)))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(calendar)

Calendar is nil and error “malformed calendar; expected end”

### Expected Behavior:

I tested parsing this calendar(from the same link) in python using the library `icalendar`, everything parsed as I needed it to.

### Minimal Example ical extract:

```ical
BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
X-WR-CALNAME:БСБО-01-21
BEGIN:VTIMEZONE
TZID:Europe/Moscow
X-LIC-LOCATION:Europe/Moscow
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTEND;TZID=Europe/Moscow;VALUE=DATE:20240324
DTSTAMP;TZID=Europe/Moscow:00010101T000000
DTSTART;TZID=Europe/Moscow;VALUE=DATE:20240323
SEQUENCE:0
SUMMARY:Все занятия в дистанционном формате
TRANSP:TRANSPARENT
UID:c68bc5ec-e46f-55ae-9f0a-9cea4365dc9b
END:VEVENT
BEGIN:VEVENT
CATEGORIES:ЛК
DESCRIPTION:Преподаватель: Корягин Сергей Викторович\n\nГруппы:\nБСБО-01-2
 1\nБСБО-02-21\nБСБО-04-21\n
DTEND;TZID=Europe/Moscow:20240902T121000
DTSTAMP:00010101T000000
DTSTART;TZID=Europe/Moscow:20240902T104000
LOCATION:455 (С-20)
RRULE:FREQ=WEEKLY;INTERVAL=2;UNTIL=20241230T210000Z
SEQUENCE:0
SUMMARY:ЛК Создание инструментальных средств разработки программного обесп
 ечения
TRANSP:OPAQUE
UID:f9de3adf-37f2-5710-abaf-27bd64443c70
X-SCHEDULE_VERSION-ID:8
END:VEVENT
BEGIN:X-SCHEDULE-VERSION
SVID:8
X-SV-END:2024-12-30T21:00:00.0000000Z
X-SV-START:2024-09-01T21:00:00.0000000Z
X-SV-TYPE:SEMESTER
END:X-SCHEDULE-VERSION
END:VCALENDAR
```

### Anything else:

`icalURL := "http://english.mirea.ru/schedule/api/ical/1/248"`

**Comment by arran4** [comment]
Will do a small test now. See if it can be quickly resolved.

**Comment by arran4** [comment]
@KirillZet  The issue is the `_` in this line:

```ical
X-SCHEDULE_VERSION-ID:8
```

Tests:

https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/calendar_test.go#L497-L525

Broken: https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/testdata/issue111/vevent2.ics

Working: https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/testdata/issue111/vevent2.ics

Which should follow the grammar: https://datatracker.ietf.org/doc/html/rfc5545

(I have extracted it to the relevant parts from section 3.1)

```
     name          = iana-token / x-name
     x-name        = "X-" [vendorid "-"] 1*(ALPHA / DIGIT / "-")
     vendorid      = 3*(ALPHA / DIGIT)
```

Alpha and digit are defined in: 

```
     ALPHA      = %x41-5A / %x61-7A   ; A-Z / a-z
     DIGIT      = %x30-39
```

Which I know sucks as an answer.

How much influence do you have over this choice of character? I will see if we can find a solution. It's not per-say a "bug" in this but I do feel that if a work around is possible I could try offer it.

I don't know `ical.net` should we ping the developer? https://github.com/ical-org/ical.net

**Comment by RegreTTO** [comment]
> Broken: https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/testdata/issue111/vevent2.ics
> 
> Working: https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/testdata/issue111/vevent2.ics

It seems, that your provided examples are the same

**Comment by arran4** [comment]
Hah.. Clipboard failure.

Try one of those against working: https://github.com/arran4/golang-ical/blob/5670d8a3f3650007bb5b3b827b7a3aead774480d/testdata/issue111/vevent2-no-desc.ics

Remember, always `^C` at least 2 times. :P

**Comment by KirillZet** [comment]
Thanks for the help)
I just replaced this line everywhere `X-SCHEDULE_VERSION-ID:8`, with this `X-SCHEDULE-VERSION-ID`,  and everything parsed as it should.

`bodyString = strings.Replace(bodyString, "X-SCHEDULE_VERSION-ID:8", "X-SCHEDULE-VERSION-ID:8", -1)`

I think everyone who faces the same problem can solve it this way. It's a bit of a crutch, but it works)

**Comment by arran4** [comment]
I think this ticket indicates 2 issues with my library:
* Bad error reporting; which is being worked on: https://github.com/arran4/golang-ical/pull/73
* Ability to make the lexer more flexible, which I have started in the blocked: https://github.com/arran4/golang-ical/pull/107 via option args.

So expect improvements.

@KirillZet were you able to find where the invalid token (name `X-SCHEDULE_VERSION-ID:8`) was being inserted? What's generating it?

**Comment by KirillZet** [comment]
> I think this ticket indicates 2 issues with my library:
> * Bad error reporting; which is being worked on: https://github.com/arran4/golang-ical/pull/73
> * Ability to make the lexer more flexible, which I have started in the blocked: https://github.com/arran4/golang-ical/pull/107 via option args. (As there is no consequence of adding that character to the token on the lexer side.)
> 
> So expect improvements.
> 
> @KirillZet were you able to find where the invalid token (name `X-SCHEDULE_VERSION-ID:8`) was being inserted? What's generating it?

The API from which I get the link to ical belongs to my university, so there's no way for me to see what's actually going on there.

**Comment by arran4** [comment]
Ah. I guess all you can do is log it. Good luck.

**Comment by KirillZet** [comment]
Hi again, I am facing the same error again and the past solution is not helping(

2024/12/19 12:47:43 malformed calendar; expected end

`icalURL := "http://english.mirea.ru/schedule/api/ical/1/698"

	resp, err := http.Get(icalURL)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	bodyString := string(body)

	bodyString = strings.Replace(bodyString, "X-SCHEDULE_VERSION-ID:8", "X-SCHEDULE-VERSION-ID:8", -1)

	println(bodyString)

	calendar, err := ics.ParseCalendar(strings.NewReader(bodyString))
	if err != nil {
		log.Fatal(err)
	}`
	
```
BEGIN:VCALENDAR
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
X-WR-CALNAME:БСБО-01-23
BEGIN:VTIMEZONE
TZID:Europe/Moscow
X-LIC-LOCATION:Europe/Moscow
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTEND;TZID=Europe/Moscow;VALUE=DATE:20240324
DTSTAMP;TZID=Europe/Moscow:00010101T000000
DTSTART;TZID=Europe/Moscow;VALUE=DATE:20240323
SEQUENCE:0
SUMMARY:Все занятия в дистанционном формате
TRANSP:TRANSPARENT
UID:c68bc5ec-e46f-55ae-9f0a-9cea4365dc9b
END:VEVENT
BEGIN:VEVENT
CATEGORIES:Экзамен
DESCRIPTION:Преподаватель: Филатов Вячеслав Валерьевич\n
DTEND;TZID=Europe/Moscow:20250129T103000
DTSTAMP;VALUE=DATE:00010101
DTSTART;TZID=Europe/Moscow:20250129T090000
LOCATION:232 (С-20)
SEQUENCE:0
SUMMARY:Экзамен Алгоритмы и структуры данных
TRANSP:OPAQUE
UID:19f8f6d3-c785-54ba-8d92-6504a484fa99
X-SCHEDULE_VERSION-ID:9
END:VEVENT
BEGIN:X-SCHEDULE-VERSION
SVID:8
X-SV-END:2024-12-30T21:00:00.0000000Z
X-SV-START:2024-09-01T21:00:00.0000000Z
X-SV-TYPE:SEMESTER
END:X-SCHEDULE-VERSION
BEGIN:X-SCHEDULE-VERSION
SVID:9
X-SV-END:2025-02-02T21:00:00.0000000Z
X-SV-START:2024-12-23T21:00:00.0000000Z
X-SV-TYPE:SESSION
END:X-SCHEDULE-VERSION
END:VCALENDAR
	
```

Is there anything you can do to help?

**Comment by arran4** [comment]
@KirillZet You re-opened this, but your message was lost?

**Comment by KirillZet** [comment]
Sorry it was an accident, I'll close it now
