### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by hrdtbs** [arran4/golang-ical#16]
Hello,

I like your golang-ical, but I really need your license. Or should this be private?
Is this an open-source and suitable for commercial use?

**Comment by arran4** [comment]
Completely forgot.. Any suggestions?

**Comment by hrdtbs** [comment]
I suggest Apache license 2.0, MIT license

https://www.apache.org/licenses/LICENSE-2.0
https://spdx.org/licenses/MIT

**Comment by arran4** [comment]
Okay. I am giving you that license as of this comment. I will add it or some other license sometime soon.

**Comment by arran4** [comment]
Done
