### ISSUE TITLE
"Import failed to save." Calendar.app on macOS Catalina (With example)

### ISSUE THREAD

**Issue by dewey** [arran4/golang-ical#19]
Hey there,

I'm trying to generate an ics file and import it into Calendar.app of macOS Catalina. I'm getting the following error for the given file:

<img width="532" alt="Screen Shot 2020-06-06 at 18 16 08" src="https://user-images.githubusercontent.com/790262/83949054-f372de00-a821-11ea-9833-de5c216d9e6a.png">

The ics file I'm trying to import is:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Arran Ubels//Golang ICS library
METHOD:REQUEST
BEGIN:VEVENT
UID:456
CREATED:20200610T181852Z
DTSTAMP:20200610T181852Z
LAST-MODIFIED:20200610T181852Z
DTSTART:20200610T181852Z
SUMMARY:Post scheduled 456
DESCRIPTION:description456
URL:456
END:VEVENT
BEGIN:VEVENT
UID:123
CREATED:20190821T080000Z
DTSTAMP:20190821T080000Z
LAST-MODIFIED:20190821T080000Z
DTSTART:20190821T080000Z
SUMMARY:Post scheduled 123
DESCRIPTION:description123
URL:123
END:VEVENT
END:VCALENDAR
```

If I remove one of the events so that there's only one in there it works:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Arran Ubels//Golang ICS library
METHOD:REQUEST
BEGIN:VEVENT
UID:456
CREATED:20200610T181852Z
DTSTAMP:20200610T181852Z
LAST-MODIFIED:20200610T181852Z
DTSTART:20200610T181852Z
SUMMARY:Post scheduled 456
DESCRIPTION:description456
URL:456
END:VEVENT
END:VCALENDAR
```

I'm running out of ideas what could cause that, it's a valid file according to: https://icalendar.org/validator.html#results

Do you have any idea what could happen there?

Thanks!

**Comment by dewey** [comment]
Just found that if I remove: `METHOD:REQUEST` it works. Maybe "Request" doesn't work if there are multiple `VEVENT` in the `VCALENDAR`.

**Comment by arran4** [comment]
Any chance you can play around with it and figure out if I have implemented it wrong?

**Comment by arran4** [comment]
@dewey No problem. Let me know if you get time to look at it. I think this library needs some love IMHO.

**Comment by starspace1** [comment]
> Just found that if I remove: `METHOD:REQUEST` it works. Maybe "Request" doesn't work if there are multiple `VEVENT` in the `VCALENDAR`.

[Yep!](https://tools.ietf.org/html/rfc2446#section-3.2.2) And THANK YOU for this comment, you made my week by getting me unstuck on an apple calendar .ics import bug with like, no documentation 🙏

**Comment by arran4** [comment]
@starspace1 Is this something the library should be picking up. (If only I could get more time to work on the library.)

**Comment by dewey** [comment]
> > Just found that if I remove: `METHOD:REQUEST` it works. Maybe "Request" doesn't work if there are multiple `VEVENT` in the `VCALENDAR`.
> 
> [Yep!](https://tools.ietf.org/html/rfc2446#section-3.2.2) And THANK YOU for this comment, you made my week by getting me unstuck on an apple calendar .ics import bug with like, no documentation 🙏

Ohh, nice find with the RFC! Good to know it's not just an obscure bug but actually the standard. Glad my stabbing in the dark was actually helpful to anyone else 😄

**Comment by arran4** [comment]
@dewey Did you need anything from me on this or can I close the issue?

**Comment by dewey** [comment]
I think you can close it. I'm not using it at the moment but at least we documented the behavior in this issue for future search engine users 😀

**Comment by arran4** [comment]
Oh okay. Wil you use it in the future?

**Comment by dewey** [comment]
Hey, unsure. My project is now built in Rails instead of Go so that's why I don't really have a use case right now. If I need a Go lib in the future I know where to look though :)

**Comment by arran4** [comment]
Thanks. I'm going to close this as there hasn't been much movement on it. Feel free to reopen it.
