### ISSUE TITLE
Better time parsing

### ISSUE THREAD

**Issue by shaohme** [arran4/golang-ical#43]
I would like to contribute a patch that expands the existing time.Time parsing in the library used for functions like GetStartAt, and GetAllDayStartAt, etc. At the moment these functions does not support timestamps and date strings like, 
```
19980118T230000 <- error: cannot parse "" as "Z"
20210527Z <- error: cannot parse "Z" as "T"
20210628 <- error: cannot parse "" as "T"
20220122T170000Z <- error: extra text: "T170000Z" (when invoking GetAllDay.*At )
```
... and probably many others.

Would you reject a PR for such a feature?

**Comment by arran4** [comment]
I don't think so. Provided it's compliant with the RFC, well written, has tests and won't break existing code.

**Comment by shaohme** [comment]
How about this #44 ?

**Comment by arran4** [comment]
Sorry for the delay. I have some questions about it. I merged another PR that kind of conflicts.

**Comment by shaohme** [comment]
It's okay. I'll look into it now.

**Comment by arran4** [comment]
Thanks.

**Comment by shaohme** [comment]
> Thanks.

It should be mergeable now
