### ISSUE TITLE
Events containing multiple `ATTENDEE`-Properties cause `Malformed Calendar`-Error

### ISSUE THREAD

**Issue by JM-Lemmi** [arran4/golang-ical#52]
This is the case for example in Google calendars, where different attendees have answered with different availibility.

[issue52_attachments.zip](https://github.com/arran4/golang-ical/files/8018926/issue52_attachments.zip)

**Comment by arran4** [comment]
Got it.. Thanks. Looking at it here: https://github.com/arran4/golang-ical/pull/53

**Comment by arran4** [comment]
Okay I managed to pinpoint it to the parsing of this:
```
;X-RESPONSE-COMMENT="Abgelehnt\, weil ich au&szlig\;er Haus bin"
```
Once that's removed it works

**Comment by arran4** [comment]
When I remove the `\` characters it parses fine:
```X-RESPONSE-COMMENT="Abgelehnt, weil ich au&szlig;er Haus bin"```

It can handle the `,` and `;` because they are quoted it seems. Escaping them seems to break it.

**Comment by arran4** [comment]
I assume these were added by Google Calendar?

**Comment by arran4** [comment]
The problem looks like I handled this way too simplistically:
```
		tokenPos = propertyParamValueReg.FindIndex([]byte(contentLine[p:]))
```
The regex doesn't consider `\;` as a possibility, as it seems that when (I think I wrote this) I wrote this I was thinking that the quotes " would be considered enough. Meaning I will have to write some sort of tokenizing logic here.

**Comment by arran4** [comment]
I believe I have solved this. Can you verify it in the PR with a couple more tests?

https://github.com/arran4/golang-ical/pull/53
