### ISSUE TITLE
Remove event from calendar

### ISSUE THREAD

**Issue by antipopp** [arran4/golang-ical#57]
Is there a way to parse a calendar and then remove some events? I don't mean to cancel them, I want them out of the .ics file.

**Comment by antipopp** [comment]
I think I've found a workaround. I'm parsing the "old" calenda, then I add the necessary events to a new calendar and return that. But I really know nothing about .ics standards and I have no idea if there is something wrong with this approach. 

Any tip regarding this?

**Comment by ManoloTonto1** [comment]
hello has this been added yet? if not I can go ahead an make a pr with an implementation to be able to remove events.

**Comment by arran4** [comment]
I would be happy to receive a PR. My contract will be ending soon so I will have time to look in more detail in this.
