### ISSUE TITLE
VTodo and VJournal Missing Setters and Getters

### ISSUE THREAD

**Issue by spslater** [arran4/golang-ical#65]
The VEvent component has most (all?) of the methods to be able to set and get the different parts of the component like the summary, description, start time, ect. It also has a way to create new events.

The VTodo and VJournal only have a way to serialize and load the information. (I think same is true with VBusy and VTimezone, but I don't need those for my project right now, so I haven't looked at them yet)

If these haven't been implemented yet because there hasn't been a need for it, then I will go ahead and work on adding this functionality.

**Comment by arran4** [comment]
You're correct:
> these haven't been implemented yet because there hasn't been a need for it

Please do, happy to accept PRs. If possible comment, but consistency with the others I think is key right now.

**Comment by quite** [comment]
Yeah, I began using golang-ical for a small project, and creating a VCAL with a VTODO component would be nice, and being able to set all props.

**Comment by arran4** [comment]
I'm currently travelling but I will see why this has stalled in a couple weeks if not sooner.

**Comment by arran4** [comment]
I believe this was partially or full resolved in: https://github.com/arran4/golang-ical/pull/90 

Can you please review and let me know?

**Comment by spslater** [comment]
Just reviewed the current code and looks like everything has the needed setters and getters. Thanks.

**Comment by arran4** [comment]
Thanks will do
