### ISSUE TITLE
Already escaped symbols get double escaped

### ISSUE THREAD

**Issue by JM-Lemmi** [arran4/golang-ical#68]
Parsing an already escaped semicolon `\;` creates a double backslah `\\;`

https://github.com/arran4/golang-ical/blob/d07bbcbc575ce4e3a9cd7ccf17236a3940b314eb/property.go#L100-L105

Probably just putting L104 to the beginning of the if statement should resolve this?

**Comment by arran4** [comment]
Ok. Bit flooded right now. But 104 does seem erroneously placed. I will get around to this, but if you do a pr that's just that and has a test case I will merge it quickly.
