### ISSUE TITLE
Properties appearing more than once

### ISSUE THREAD

**Issue by fleaz** [arran4/golang-ical#89]
Hey,

first of all thanks for this library. I know how hard iCAL can be :D 

I was trying to check if a repeated event has been deleted and wanted to access the "EXDATE" property. 
According to the [RFC](https://www.rfc-editor.org/rfc/rfc5545#section-3.6.1), some properties CAN occur more than once like e.g. EXDATE, but with the `GetProperty()` function I will always only get the first entry of an event and not all of them. Depending on the library which generated the ical file, the EXDATE can either appear only once and have all dates comma separated in a single line or appear multiple times with only a single date, which to my knowledge is both RFC compliant.

I have tested an ical File from NextCloud and from DaviCAL and both use the style with single dates in separate EXDATE entries. If you need something to test, here is a simple calendar from my NextCloud with a repeating event and two EXDATE entries: https://dump.felixbreidenstein.de/test.ics

Best,
Felix

**Comment by arran4** [comment]
Thanks. This will require a bit of work. Reading the spec it opens the doors to a "validator" too.

**Comment by arran4** [comment]
Please review: https://github.com/arran4/golang-ical/pull/108  and let me know if that is good and fully satisfies this issue.
