### ISSUE TITLE
How to update ical event

### ISSUE THREAD

**Issue by mrLSD** [arran4/golang-ical#9]
It's look awesome library.
Could you provide flow for updating existed event?
When I tried update ical with same UUID Google Calendar create new event but not update existed event.

**Comment by arran4** [comment]
Interesting.. Do you know what I'm missing. Do you have a small-as-possible example?

**Comment by arran4** [comment]
Hi?

**Comment by mrLSD** [comment]
Hi, I found that it was simple bug it was different UUID. So for Google Calendar it's work.
But it dosen't work for Outlook. For some reason it not recognize Calendar Event.
And I can't figure out WTF. ))

**Comment by arran4** [comment]
Was it a library bug or something which should be documented?

What version of outlook? Desktop, web, 365?

**Comment by arran4** [comment]
hi @mrLSD 
I will close this on or after the 15th of February if I haven't heard from you.
